---
title: "assignment2"
author: "Sang Don Kim"
output:
  word_document: default
  html_document:
    df_print: paged
---



### 3.3 

```{r,message=FALSE}
library(mvtnorm)
library(EnvStats)
```

```{r}
n <- 1000
u <- runif(n)
a <- 2
b <- 2
X <- b/(1-u)^(1/a)
x <- seq(0, 2000, 0.1)

pareto <- function(x) { 
        a*b^a/x^(a+1)
}

hist(X, prob = T , breaks = 50,ylim = c(0,1), main = 'Pareto distribution')
lines(x, pareto(x), col = 'blue')


```


### 3.5 

```{r}
n <- 1000
u <- runif(n)

u[u<0.1] <-  0
u[u>=0.1 & u<0.3] <-  1
u[u>=0.3 & u<0.5] <-  2
u[u>=0.5 & u<0.7] <- 3
u[u>=0.7 & u<1] <- 4

par(mfrow = c(1,2))
barplot(table(u), main = 'Inverse transform method')
y <- sample(0:4, size = n, replace = T, prob = c(0.1, 0.2, 0.2, 0.2, 0.3))
barplot(table(y), main = 'empirical distribution')
par(mfrow=c(1,1))
```

 
 
### 3.7 

```{r}
n <- 1000
k <- 0
j <- 0
y <- numeric(n)

while (k<n) {
        u <- runif(1)
        j <- j+1
        x <- runif(1)
        if (12*x^2*(1-x)/2>u) { # c=2
                k <- k+1
                y[k] <- x
        }
        
}


beta <- function(x, a, b) {
        factorial(a+b-1)/factorial(a-1)*factorial(b-1)*x^(a-1)*(1-x)^b-1
}

hist(y, freq = F, breaks = 30, ylim = c(0,2))
lines(density(rbeta(n, 3, 2)), col = 'blue')

```




### 3.11

```{r}
n <- 1000
x1 <- rnorm(n, 0, 1)
x2 <- rnorm(n, 3, 1)

k <- sample(0:1, size = n, replace = T, prob = c(0.75, 0.25))
x <- c(x1[k==0], x2[k==1])
plot(density(x), main = '')
par(new = T)
hist(x, prob = T, breaks = 30, main = 'normal location mixture')

p <- c(0.7, 0.65, 0.6, 0.55, 0.5, 0.45, 0.4, 0.35, 0.3)

par(mfrow = c(3,3))
for (i in p) {
  k <- sample(0:1, size = n, replace = T, prob = c(i, 1-i))
  x <- c(x1[k==0], x2[k==1])
  plot(density(x), main = '')
  par(new = T)
  hist(x, prob = T, breaks = 50, main = i)
}

```





### 3.14

```{r}
u <- c(0, 1, 2)
s <- matrix(c(1, -0.5, 0.5, -0.5, 1, -0.5, 0.5, -0.5, 1), nrow = 3)

rmvn.Choleski <- 
        function(n, mu, Sigma){
                d <- length(mu) 
                Q <- chol(Sigma) # choleski factorization of Sigma 
                Z <- matrix(rnorm(n*d), nrow = n, ncol = d) # multivariate standard normal dist(n*d)
                X <- Z%*%Q + matrix(mu, n, d, byrow = T) # X=ZQ+Ju^t
                X
        }

X <- rmvn.Choleski(200, u, s)
pairs(X)


colMeans(X) # 촐레스키 분해로 구한 X의 평균은 초기에 설정한 모수 u에 거의 근사한다.  
u
cov(X) # 촐레스키 분해로 구한 X의 covariance matrix는 초기에 설정한 s에 거의 근사한다.
s
```