---
title: "untitled"
author: "Sang Don Kim"
mainfont: NanumGothic
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
latex_engine: xelatex
---


## pr 11.3

```{r}

m <- 10000
x <- numeric(m)
x[1] <- rnorm(1) # common support를 가지는 제안분포
k <- 0
u <- runif(m)

for (i in 2:m) {
        xt <- x[i-1]
        y <- rnorm(1)
        num <- dcauchy(y, location = 0, scale = 1)*dnorm(xt)
        den <- dcauchy(xt, location = 0, scale = 1)*dnorm(y)
        if (u[i] <= num/den) {
                x[i] <- y
        } else {
                x[i] <- xt
                k <- k+1
        }
}
print(paste('기각 비율 :',  k))  

b <- 1001 # 앞에 1000개를 임의로 버림 
y <- x[b:m]
a <- ppoints(10); a # 십분위수 계산 

QR <- qt(a, df = 1); QR # theoretical
Q <- quantile(y, a) # empirical

qqplot(QR, Q, main = '', cex = 0.5, xlab = 'Cauchy Quantiles', ylab = 'Sample Quantiles')
abline(0,1) 

```


## pr 11.9

```{r}

N <- 10000               
burn <- 2000            
X <- matrix(0, N, 2)    

rho <- 0.9             
mu1 <- 0
mu2 <- 0
sigma1 <- 1
sigma2 <- 1
s1 <- sqrt(1-rho^2)*sigma1
s2 <- sqrt(1-rho^2)*sigma2


X[1, ] <- c(mu1, mu2) # 초기값

for (i in 2:N) {
        x2 <- X[i-1, 2] # x2가 주어짐
        m1 <- mu1 + rho * (x2 - mu2) * sigma1/sigma2 # x2가 주어졌을 때 x1 조건부 분포의 평균 
        X[i, 1] <- rnorm(1, m1, s1) # 조건부 분포로 생성된 x1 업데이트 
        x1 <- X[i, 1]
        m2 <- mu2 + rho * (x1 - mu1) * sigma2/sigma1 # x1이 주어졌을 때 x2 조건부 분포의 평균
        X[i, 2] <- rnorm(1, m2, s2) # 조건부 분포로 생성된 x1 업데이트
}

b <- burn + 1
x <- X[b:N, ] # 1000개 버림

plot(x, main = '', cex = 0.5, xlab = bquote(X[1]), ylab = bquote(X[2]), ylim = range(x[, 2]))

X <- data.frame(x=X[,1], y = X[,2])
head(X)

fit <- lm(y~x, X)
par(mfrow = c(2, 2))
plot(fit)
```


## pr 11.12

```{r}

f <- function(x, sigma){
        if (any(x<0)) return(0)
        stopifnot(sigma>0)
        return((x/sigma^2)*exp(-x^2/(2*sigma^2)))
}

chain <- function(sigma, N, X1){ # N : length, X1 : 초기값, sigma : normal 표준편차 
        x <- rep(0, N)
        x[1] <- X1
        u <- runif(N)
        
        for (i in 2:N) {
                xt <- x[i-1]
                y <- rchisq(1, df = xt)  
                r1 <- f(y, sigma)*dchisq(xt, df = y)
                r2 <- f(xt, sigma)*dchisq(y, df = xt)
                r <- r1/r2
                if (u[i]<=r) {
                        x[i] <- y
                } else {
                        x[i] <- xt
                }
        }
        return(x)
}

sigma <- 4
k <- 4
n <- 15000
b <- 1000

x0 <- c(2, 4, 6, 8) # 극단값으로 초기값 부여  
X <- matrix(0, nrow = k, ncol = n) # 4x15000
for (i in 1:k) {
        X[i, ] <- chain(sigma, n, x0[i]) # 체인 4개 생성 
}

psi <- t(apply(X, 1, cumsum)) # 각 체인의 누적합

for (i in 1:nrow(psi)) {
        psi[i, ] <- psi[i, ]/(1:ncol(psi))
}

Gelman.Rubin <- function(psi){
        psi <- as.matrix(psi) # 4x15000
        n <- ncol(psi)
        k <- nrow(psi)
        i <- 3
        # psi : 4 x 15000
        while (TRUE) {
                psi_iter <- psi[,(1:i)]
                psi.means <- rowMeans(psi_iter)
                B <- n*var(psi.means)
                psi.w <- apply(psi_iter, 1, 'var')
                W <- mean(psi.w)
                v.hat <- W*(n-1)/n+(B/n)  
                r.hat <- v.hat/W
                if (r.hat<=1.2) {
                        break
                }
                i <- i+1
        }
        result <- data.frame(rhat = r.hat, length = i)
        return(result)
}


Gelman.Rubin(psi)


```

